# Generated by Django 4.2.7 on 2023-11-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trader',
        ),
    ]
